services:
  host:
    build:
      context: .
      dockerfile: Company.Ecommerce/Dockerfile
    container_name: company-ecommerce-host
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ORDERS_DB_CONNECTION=Server=db;Database=OrdersDb;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=false;
      - AUTH_AUTHORITY=http://keycloak:8080/realms/company
      - AUTH_AUDIENCE=company-ecommerce
      - AUTH_REQUIRE_HTTPS=false
    depends_on:
      - db
      - keycloak

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: company-ecommerce-db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    container_name: company-ecommerce-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  dbdata:
  keycloak_data:
